### ISSUE TITLE
Crash after changing desktop with keybind

### ISSUE THREAD

**Issue by natemaia** [natemaia/kickshaw#1]
Can't recreate in i3, possibly only in openbox
Edit: referenced here
https://plus.google.com/u/0/+AdhiPambudi/posts/T52opMcJH64

Edit #2: After trying on openbox to get it to crash I wasn't successful..
Possibly related to the menu it's trying to edit?

**Comment by addy-dclxvi** [comment]
I have tried to replace my menu.xml to default ARCHLabs menu.xml, remove ~/.kickshawrc, do openbox reconfigure, then launch Kickshaw again.
Hit Ctrl+Alt+Right, then Ctrl+Alt+Left, open a combobox. It crashes again.

Then I replace ARCHLabs default menu.xml with your menu.xml from my-dots repo. Do the same method, it crashes again.

Maybe one of my Openbox configs has been polluted, too much tweak. I will try to install it to ARCHLabs live usb. Maybe tonight, still AFK.

This is my menu.xml
https://github.com/addy-dclxvi/Ultimate-Dotfiles/blob/master/.config/openbox/menu.xml

Can't upload the ~/.kickshawrc file, still away from keyboard.

**Comment by natemaia** [comment]
I'll do some more testing tonight to see if I can find the issue.

I wasn't using keybinds to shift workspaces so possibly this is the problem.

**Comment by natemaia** [comment]
So after alot of testing I was able to recreate this with relative consistency.
The issue lies somewhere within using a keybind to switch workspaces at which point it tries to access memory that it cannot or does not exist, resulting in a segfault.

**Comment by addy-dclxvi** [comment]
Yes, I'm using keybinds to shift workspaces.
And yes, I got the message and I made it doesn't appear again on the next launch.

Glad to know that You have known the cause of the problem. I want to help, but it is so advanced technical things. My knowledge still can't reach that.
